In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/Bank_Churn.csv')

In [33]:
df.dtypes

CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [36]:
df.values

array([[15634602, 'Hargrave', 619, ..., 1, 101348.88, 1],
       [15647311, 'Hill', 608, ..., 1, 112542.58, 0],
       [15619304, 'Onio', 502, ..., 0, 113931.57, 1],
       ...,
       [15584532, 'Liu', 709, ..., 1, 42085.58, 1],
       [15682355, 'Sabbatini', 772, ..., 0, 92888.52, 1],
       [15628319, 'Walker', 792, ..., 0, 38190.78, 0]], dtype=object)

In [37]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [38]:
df.tail()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [39]:
df.head(5)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [40]:
df.value_counts()

CustomerId  Surname   CreditScore  Geography  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
15815316    Kennedy   644          France     Male    50   9       76817.00   4              1          0               196371.13        1         1
15815295    John      662          France     Female  38   2       96479.81   1              1          0               120259.41        0         1
15815271    Ritchie   755          Germany    Male    43   6       165048.50  3              1          0               16929.41         1         1
15815259    Fang      835          France     Female  56   2       0.00       2              1          1               39820.13         0         1
15815236    Chiganu   574          Spain      Male    34   5       0.00       2              0          0               28269.86         0         1
                                                                                                                                                  ..
15565796    Docherty  745          Germany    Male    48   10      96048.55   1              1          0               74510.65         0         1
15565779    Kent      627          Germany    Female  30   6       57809.32   1              1          0               188258.49        0         1
15565714    Cattaneo  601          France     Male    47   1       64430.06   2              0          1               96517.97         0         1
15565706    Akobundu  612          Spain      Male    35   1       0.00       1              1          1               83256.26         1         1
15565701    Ferri     698          Spain      Female  39   9       161993.89  1              0          0               90212.38         0         1
Name: count, Length: 10000, dtype: int64