In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/Benefits.csv')

In [42]:
df.size

92663

In [43]:
df.nunique()

rownames    4877
stateur      109
statemb      139
state         51
age           42
tenure        41
joblost        4
nwhite         2
school12       2
sex            2
bluecol        1
smsa           2
married        2
dkids          2
dykids         2
yrdispl       10
rr          2468
head           2
ui             2
dtype: int64

In [44]:
df.copy()

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,4873,7.4,168,33,35,12,slack_work,yes,yes,female,yes,yes,no,yes,no,6,0.463557,yes,yes
4873,4874,7.0,189,74,39,5,slack_work,no,no,male,yes,yes,yes,no,no,4,0.393750,yes,yes
4874,4875,8.0,168,74,59,13,slack_work,no,no,male,yes,yes,yes,yes,no,2,0.372428,yes,yes
4875,4876,6.3,191,41,33,11,slack_work,no,no,male,yes,yes,yes,yes,yes,3,0.500000,yes,no
4876,4877,9.3,188,94,27,2,other,no,no,male,yes,yes,yes,yes,yes,7,0.495413,yes,yes

In [45]:
df.ndim

2

In [46]:
df.sample()

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
523,524,7.2,166,93,54,2,slack_work,no,no,male,yes,yes,yes,yes,no,4,0.332,yes,yes

In [47]:
df.describe()

,rownames,stateur,statemb,state,age,tenure,yrdispl,rr
count,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000
mean,2439.000000,7.511031,180.660242,52.808079,36.129998,5.664138,5.203609,0.438366
std,1408.012962,2.500579,43.241595,25.834967,10.600737,6.279938,3.095116,0.106194
min,1.000000,2.200000,84.000000,11.000000,20.000000,1.000000,1.000000,0.038610
25%,1220.000000,5.700000,150.000000,31.000000,28.000000,2.000000,2.000000,0.375212
50%,2439.000000,7.200000,177.000000,55.000000,34.000000,3.000000,5.000000,0.490446
75%,3658.000000,9.000000,205.000000,74.000000,43.000000,7.000000,8.000000,0.511574
max,4877.000000,18.000000,293.000000,95.000000,61.000000,41.000000,10.000000,0.691176

In [48]:
df.isnull()

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4873,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4874,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4875,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4876,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [49]:
df.memory_usage()

Index         132
rownames    39016
stateur     39016
statemb     39016
state       39016
age         39016
tenure      39016
joblost     39016
nwhite      39016
school12    39016
sex         39016
bluecol     39016
smsa        39016
married     39016
dkids       39016
dykids      39016
yrdispl     39016
rr          39016
head        39016
ui          39016
dtype: int64