In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/BEPS.csv')

In [70]:
df.sample()

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
1185,1186,Labour,42,3,3,4,4,3,10,2,female

In [71]:
df.nunique()

rownames                   1525
vote                          3
age                          70
economic.cond.national        5
economic.cond.household       5
Blair                         5
Hague                         5
Kennedy                       5
Europe                       11
political.knowledge           4
gender                        2
dtype: int64

In [72]:
df.size

16775

In [73]:
df.ndim

2

In [74]:
df.copy()

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male
...,...,...,...,...,...,...,...,...,...,...,...
1520,1521,Conservative,67,5,3,2,4,4,11,3,male
1521,1522,Conservative,73,2,2,4,4,4,8,2,male
1522,1523,Labour,37,3,3,5,4,4,2,2,male
1523,1524,Conservative,61,3,3,1,4,1,11,2,male
1524,1525,Conservative,74,2,3,2,4,4,11,0,female

In [75]:
df.describe()

,rownames,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge
count,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000
mean,763.000000,54.182295,3.245902,3.140328,3.334426,2.746885,3.135082,6.728525,1.542295
std,440.373894,15.711209,0.880969,0.929951,1.174824,1.230703,1.081997,3.297538,1.083315
min,1.000000,24.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,382.000000,41.000000,3.000000,3.000000,2.000000,2.000000,2.000000,4.000000,0.000000
50%,763.000000,53.000000,3.000000,3.000000,4.000000,2.000000,3.000000,6.000000,2.000000
75%,1144.000000,67.000000,4.000000,4.000000,4.000000,4.000000,4.000000,10.000000,2.000000
max,1525.000000,93.000000,5.000000,5.000000,5.000000,5.000000,5.000000,11.000000,3.000000

In [76]:
df.isnull()

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1520,False,False,False,False,False,False,False,False,False,False,False
1521,False,False,False,False,False,False,False,False,False,False,False
1522,False,False,False,False,False,False,False,False,False,False,False
1523,False,False,False,False,False,False,False,False,False,False,False
1524,False,False,False,False,False,False,False,False,False,False,False

In [77]:
df.memory_usage()

Index                        132
rownames                   12200
vote                       12200
age                        12200
economic.cond.national     12200
economic.cond.household    12200
Blair                      12200
Hague                      12200
Kennedy                    12200
Europe                     12200
political.knowledge        12200
gender                     12200
dtype: int64