In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_excel('/Coffee Shop Sales.xlsx')

In [80]:
df.shape

(149116, 11)

In [81]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [82]:
df.value_counts()

transaction_id  transaction_date  transaction_time  transaction_qty  store_id  store_location   product_id  unit_price  product_category    product_type           product_detail
149456          2023-06-30        20:57:19          2                8         Hell's Kitchen   64          0.80        Flavours            Regular syrup          Hazelnut syrup                 1
1               2023-01-01        07:06:11          2                5         Lower Manhattan  32          3.00        Coffee              Gourmet brewed coffee  Ethiopia Rg                    1
2               2023-01-01        07:08:56          2                5         Lower Manhattan  57          3.10        Tea                 Brewed Chai tea        Spicy Eye Opener Chai Lg       1
3               2023-01-01        07:14:04          2                5         Lower Manhattan  59          4.50        Drinking Chocolate  Hot chocolate          Dark chocolate Lg              1
4               2023-01-01        07:20:24          1                5         Lower Manhattan  22          2.00        Coffee              Drip coffee            Our Old Time Diner Blend Sm    1
                                                                                                                                                                                                 ..
17              2023-01-01        07:59:58          1                5         Lower Manhattan  79          3.75        Bakery              Scone                  Jumbo Savory Scone             1
16              2023-01-01        07:59:58          2                5         Lower Manhattan  47          3.00        Tea                 Brewed Green tea       Serenity Green Tea Lg          1
15              2023-01-01        07:52:36          2                5         Lower Manhattan  87          3.00        Coffee              Barista Espresso       Ouro Brasileiro shot           1
14              2023-01-01        07:48:19          1                5         Lower Manhattan  57          3.10        Tea                 Brewed Chai tea        Spicy Eye Opener Chai Lg       1
13              2023-01-01        07:45:51          1                5         Lower Manhattan  51          3.00        Tea                 Brewed Black tea       Earl Grey Lg                   1
Name: count, Length: 149116, dtype: int64

In [83]:
df.tail()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [85]:
df.sum(numeric_only=True)

transaction_id     1.114454e+10
transaction_qty    2.144700e+05
store_id           7.965870e+05
product_id         7.145431e+06
unit_price         5.043430e+05
dtype: float64

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB

In [88]:
df.median(numeric_only=True)

transaction_id     74727.5
transaction_qty        1.0
store_id               5.0
product_id            47.0
unit_price             3.0
dtype: float64

In [90]:
df.mean(numeric_only=True)

transaction_id     74737.371872
transaction_qty        1.438276
store_id               5.342063
product_id            47.918607
unit_price             3.382219
dtype: float64